matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: java
      jdk: oraclejdk8
    - os: linux
      dist: bionic
      sudo: required
      language: java
      jdk: openjdk11

#php: 7.1

#services:
#  - mysql



before_script:
  # for debugging purposes
  - php --version
  - php-cgi --version
  - which php-cgi
  - chmod +x gradlew

script:
  # Regular test suite
  - ./gradlew test
  # Launch a server
  #- ./gradlew clean tomcatRun
  # Some debug to see if server has started
  #- sudo netstat -nlp | grep :8093
  #- cat ./tomcat.log
  # debug travis
  # - sudo netstat -nlp
  # Launch the soluble-japha test suite
  - sudo -E env "PATH=$PATH" ./.travis/run_soluble_japha_phpunit_tests.sh

after_failure:
  - cat ./tomcat.log

after_success:
  #- ./gradlew build jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)


